### ISSUE TITLE
Add a simple way to version tag payloads

### ISSUE THREAD

**Issue by fjtc** [interlockledger/go-iltags#3]
Add a simple way to version tag payloads. The current suggestion is to format the payload with a version prefix and a way to put the actual payload after that.

**Comment by fjtc** [comment]
This implementation will use generics as a way to simplify its usage.

**Comment by monoman** [comment]
In C#, most payloads derive from VersionedPayload, which assumes the first field (Version) is an unsigned short int (16 bits) tag (id 5), with the version number. And this value is used to direct the serialization/deserialization of the remaining fields.
Different from your implementation Version is a tag itself and occupies 3 bytes. This was done to be more compatible in parsing alongside previously unversioned payloads.
